### PR TITLE
Made it cross-OS compatible

### PR DESCRIPTION
**Pull request by Sh-wayz**

### CODE REVIEW

**Comment by seven7ty** [comment]
nice 👍

**Comment by kevinjosethomas** [comment]
Looks good to me. Has this been tested (on multiple OS')?

**Comment by Sh-wayz** [comment]
I tested on linux but the purpose of Path is to make it cross-os so I'm assuming it does its job

**Comment by kevinjosethomas** [comment]
Sounds good 👍

**Pull request merged**
